### ISSUE TITLE
Figure out why the QR code does not work as a Aragon plugin

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/aragon-node-list#24]
deadline:11/19/18

**Comment by asoltys** [comment]
I think we'll need to patch the aragon wrapper with my changes here: https://github.com/aragon/aragon/pull/378 

I asked the aragon team to hold off on merging this upstream until I could confirm why it wasn't working in Chromium which I later figured was because we weren't using https. Let's try it out and see! If it does work with https then I'll update the pull request there and ask them to merge it.

**Comment by asoltys** [comment]
Fixed by https://github.com/althea-mesh/aragon-node-list/commit/90b278fe9514a2255f15b943e6dd72ea3fe5f351
